### ISSUE TITLE
wait function not working

### ISSUE THREAD

**Issue by evbo** [kevlened/sikuli_cpython#7]
The wait function does not define the duration variable:

```
def wait(target_string, *args, **kwargs):
    if not duration and duration != 0:
        duration = 5000
    target = Pattern(target_string).getTarget()
    screen = DesktopScreenRegion()
    return screen.wait(target, duration)
```

Also, the Pattern().getTarget() crashes causing a jvm error.

**Comment by mnovait** [comment]
this doesn't solve for me:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Traceback (most recent call last):
  File "sikuli_nounittest.py", line 16, in <module>
    main()
  File "sikuli_nounittest.py", line 6, in main
    wait("file:///bla/bla/blabla/blabla/blablabla.png", 60)
  File "/usr/lib/python2.7/sikuli/sikuli.py", line 41, in wait
    if not duration and duration != 0:
UnboundLocalError: local variable 'duration' referenced before assignment
```

**Comment by lucagiove** [comment]
submitted a patch for the wait function together with @mnovait

**Comment by lucagiove** [comment]
actually noticed that some bugfix and improvements have been committed in a fork from @flycodepl https://github.com/flycodepl/sikuli_cpython.
I already asked via mail if he could submit a pullrequest
